"use client";
import { ThemeProvider } from "@mui/material";
import "./globals.css";
import theme from "./theme";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider theme={theme}>
      <html lang="en">
        <body id="__next">{children}</body>
      </html>
    </ThemeProvider>
  );
}
